on:
  workflow_call:
    inputs:
      test-path:
        required: false
        type: string
        default: test
      python-version:
        required: false
        type: string
        default: '3.x'
      requirements-path:
        required: false
        type: string
        default: ./requirements.txt

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run unit tests with pytest
        run: |
          python -m pytest test
      

