on:
  workflow_call:
    inputs:
      test-path:
        required: false
        type: string
        default: test
      python-version:
        required: false
        type: string
        default: '3.x'
      requirements-path:
        required: false
        type: string
        default: ./requirements.txt
      target-branch:
        required: false
        type: string
        default: main

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ${{ inputs.requirements-path }}
      - name: Run unit tests with pytest
        run: |
          python -m pytest ${{ inputs.test-path }}
      - name: Check if PR exists
        id: check
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          prs=$(gh pr list \
              --repo "$GITHUB_REPOSITORY" \
              --head dev \
              --base main \
              --json title  \
              --jq 'length' \
              -S "in:title Tested Pull Request Dev -> Main")
          if [[ $prs > 0 ]]; then
              echo "skip=true" >> "$GITHUB_OUTPUT"
          fi
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        if: '!steps.check.outputs.skip'
        with:
          branch: ${{ inputs.target-branch }}
          base: dev
          title: Tested Pull Request Dev -> Main
      
