on:
  workflow_call:
    inputs:
      test-path:
        required: false
        type: string
        default: test
      python-version:
        required: false
        type: string
        default: '3.x'
      requirements-path:
        required: false
        type: string
        default: ./requirements.txt
      target-branch:
        required: false
        type: string
        default: main

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run unit tests with pytest
        run: |
          python -m pytest ${{ inputs.test-path }}
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          branch: main
          base: dev
          title: Tested Pull Request Dev -> Main
      
